services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - app_network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://youruser:yourpass@db:5432/dictionary_db
      - PORT=8080
      - NODE_ENV=development
      - OPENAI_API_KEY=
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - app_network

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpass
      - POSTGRES_DB=dictionary_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data: