services:
  # Frontend Service
  - type: web
    name: frontend
    runtime: docker
    repo: https://github.com/fatihmutluu/latin-turkish-idct/frontend # Değiştirin
    rootDir: frontend
    dockerfilePath: Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: http://backend:8080
    scaling:
      minInstances: 1
      maxInstances: 2
      targetCPUPercent: 60 # CPU kullanımı %60'a ulaştığında ölçeklensin
    healthCheckPath: / # Sağlık kontrolü

  # Backend Service
  - type: web
    name: backend
    runtime: docker
    repo: https://github.com/fatihmutluu/latin-turkish-idct/backend # Değiştirin
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dictionary-db
          property: connectionString
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: development
      - key: OPENAI_API_KEY
        sync: false # Hassas bilgiyi Render'da tanımlayın
    scaling:
      minInstances: 1
      maxInstances: 2
      targetMemoryPercent: 70 # Bellek kullanımı %70'e ulaştığında ölçeklensin
    healthCheckPath: /api/health # Sağlık kontrolü endpoint'i

databases:
  # PostgreSQL Database
  - name: dictionary-db
    databaseName: dictionary_db
    user: youruser
    plan: free
    diskSizeGB: 10
    ipAllowList: [] # Sadece özel bağlantılara izin ver