services:
  # Frontend Service
  - type: web
    name: frontend
    runtime: docker
    repo: https://github.com/your-repo/frontend # Değiştirin
    rootDir: frontend
    dockerfilePath: Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: http://backend:8080
    scaling:
      minInstances: 1
      maxInstances: 2
    healthCheckPath: / # Sağlık kontrolü
    buildCommand: yarn install
    startCommand: yarn dev

  # Backend Service
  - type: web
    name: backend
    runtime: docker
    repo: https://github.com/your-repo/backend # Değiştirin
    rootDir: backend
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dictionary-db
          property: connectionString
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: development
      - key: OPENAI_API_KEY
        sync: false # Hassas bilgiyi Render'da tanımlayın
    scaling:
      minInstances: 1
      maxInstances: 2
    healthCheckPath: /api/health # Sağlık kontrolü endpoint'i
    buildCommand: yarn install
    startCommand: yarn start

databases:
  # PostgreSQL Database
  - name: dictionary-db
    databaseName: dictionary_db
    user: youruser
    plan: free
    diskSizeGB: 10
    ipAllowList: [] # Sadece özel bağlantılara izin ver